### PR TITLE
Changes to support GCC support in the makefiles for build.  Minor path changes and settings var changes.

### PR DESCRIPTION
**Pull request by mrmowgli**
Build should work now.  However I did add sudo to a couple of the dfu-util lines until I understand what's going on with the udev rules.

### CODE REVIEW

**Comment by nrobinson2000** [comment]
Uhh.  Now Circle Ci fails.  I'll check this on my Linux machine to see if it works.

**Comment by nrobinson2000** [comment]
It fails on Linux.

```
$po photon clean

Linux detected... 
 Setting our paths for gcc-arm-none-eabi 
/home/nrobinson/po-util.sh: line 87: export: -e: invalid option
export: usage: export [-fn] [name[=value] ...] or export -p

  Path Set. 
 photon selected. 
Already on 'latest'
Your branch is up-to-date with 'origin/latest'.
Building firmware for Spark core, platform ID: 0, product ID: 0
make -C ./communication clean
/bin/sh: 1: arm-none-eabi-gcc: not found
make[1]: Entering directory `/home/nrobinson/github/firmware/communication'
/home/nrobinson/github/firmware/build/arm-tools.mk:43: *** "ARM gcc version 4.8.4 or later required, but found ". Stop.
make[1]: Leaving directory `/home/nrobinson/github/firmware/communication'
make: *** [clean_communication] Error 2
```

**Comment by nrobinson2000** [comment]
I don't think that the `-e` is necessary.  I'll try to fix this.

**Comment by nrobinson2000** [comment]
Fails again...

```
nrobinson@mint-desktop:~ $ po photon clean
 Linux detected... 
 Setting our paths for gcc-arm-none-eabi 
/home/nrobinson/bin/gcc-arm-embedded/gcc-arm-none-eabi-4_8-2014q2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
  Path Set. 
 photon selected. 
Already on 'latest'
Your branch is up-to-date with 'origin/latest'.
Building firmware for Spark core, platform ID: 0, product ID: 0
make -C ./communication clean
/bin/sh: 1: /home/nrobinson/bin/gcc-arm-embedded/gcc-arm-none-eabi-4_8-2014q2/binarm-none-eabi-gcc: not found
make[1]: Entering directory `/home/nrobinson/github/firmware/communication'
/home/nrobinson/github/firmware/build/arm-tools.mk:43: *** "ARM gcc version 4.8.4 or later required, but found ". Stop.
make[1]: Leaving directory `/home/nrobinson/github/firmware/communication'
make: *** [clean_communication] Error 2
```

**Comment by nrobinson2000** [comment]
It appears that ~/bin is not created and gcc-arm-embedded is not installed.

**Comment by nrobinson2000** [comment]
Also on line 87, you had forgotten the slash at the end:

```
    export GCC_ARM_PATH=$BINDIR/gcc-arm-embedded/$GCC_ARM_VER/bin/
```

That was one of the errors.

**Comment by nrobinson2000** [comment]
I still think something strange is happening with `$BINDIR`

**Comment by nrobinson2000** [comment]
The `~/bin` seems to get deleted after `po photon clean`

```
nrobinson@mint-desktop:~/github/po-util/build-test $ po photon build
 Linux detected... 
 Setting our paths for gcc-arm-none-eabi 
/home/nrobinson/bin/gcc-arm-embedded/gcc-arm-none-eabi-4_8-2014q2/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
  Path Set. 
 photon selected. 
Already on 'latest'
Your branch is up-to-date with 'origin/latest'.
 Found firmware directory 
 Using gcc-arm from:  
Building firmware for Production Photon, platform ID: 6, product ID: 6
/bin/sh: 1: /home/nrobinson/bin/gcc-arm-embedded/gcc-arm-none-eabi-4_8-2014q2/bin/arm-none-eabi-gcc: not found
/home/nrobinson/github/firmware/build/arm-tools.mk:43: *** "ARM gcc version 4.8.4 or later required, but found ". Stop.
make: *** [communication] Error 2
```

**Comment by nrobinson2000** [comment]
Fixed it.  Travis is still failing, but whatever.

**Comment by mrmowgli** [comment]
ok, interesting chicken and egg problem.  the -e is there because make needs the variable override to compile, otherwise it defaults to the system version.

**Comment by mrmowgli** [comment]
http://ftp.gnu.org/old-gnu/Manuals/make-3.79.1/html_chapter/make_6.html#SEC68

**Comment by nrobinson2000** [comment]
I see.  However I don't believe that `-e` is a valid option in `export`, as it gave an error when it was there.

**Comment by mrmowgli** [comment]
Ah it worked over here. Hrmmm.

**Pull request merged**
