### PR TITLE
Updated vocabulary aimed at security minded folks.

### PR DESCRIPTION
**Pull request by mrmowgli**
To satisfy the security oriented people, as a reasonable trade off versus security,

### CODE REVIEW

**Comment by nrobinson2000** [comment]
This is great!

**Comment by nrobinson2000** [comment]
Would it be better to tell people to make an alias than to add it to their PATH?

**Comment by nrobinson2000** [comment]
@mrmowgli, [`download-po-util.sh`](https://github.com/nrobinson2000/po-util/blob/master/download-po-util.sh) takes care of downloading and installing `po-util` by downloading directly from GitHub.  We should tell people to use it.

**Comment by mrmowgli** [comment]
I know. Perhaps make that stick out a bit on the main page?  The Arm
toolchain isn't downloaded from there, and neither is the node.js bits,
hence my phrasing.
On Jun 17, 2016 7:01 AM, "Nathan Robinson" notifications@github.com wrote:

@mrmowgli https://github.com/mrmowgli, download-po-util.sh
https://github.com/nrobinson2000/po-util/blob/master/download-po-util.sh
takes care of downloading and installing po-util by downloading directly
from GitHub.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
https://github.com/nrobinson2000/po-util/pull/19#issuecomment-226776594,
or mute the thread
https://github.com/notifications/unsubscribe/ABy6x92jsx580glsagSDvzIQDKNKsFPTks5qMqitgaJpZM4I37zA
.

**Comment by nrobinson2000** [comment]
I made it so that po-util technically no longer requires `download-po-util.sh` because it moves `po-util.sh` to the correct place and makes the `po` alias in `.bashrc` in the install command.

So just downloading po-util and running `./po-util.sh install` does it all.

**Pull request merged**
