### PR TITLE
Another change, this time making make use environment vars.

### PR DESCRIPTION
**Pull request by mrmowgli**
Build should work now.  Third time is the charm :)

### CODE REVIEW

**Comment by nrobinson2000** [comment]
Fails. 😢

**Comment by mrmowgli** [comment]
Mother of $*&#!!

**Comment by nrobinson2000** [comment]
Weird error though:

```
photon selected. 
Branch latest set up to track remote branch latest from origin.
Switched to a new branch 'latest'
 Found firmware directory 
 Using gcc-arm from: /home/ubuntu/bin/gcc-arm-embedded/gcc-arm-none-eabi-4_8-2014q2/bin//arm-none-eabi-gcc 
 GCC_ARM_PATH=/home/ubuntu/bin/gcc-arm-embedded/gcc-arm-none-eabi-4_8-2014q2/bin/ 
Building firmware for Production Photon, platform ID: 6, product ID: 6
src/main.c: In function 'main':
src/main.c:136:52: error: 'BOOTLOADER_VERSION' undeclared (first use in this function)
     if (SYSTEM_FLAG(Bootloader_Version_SysFlag) != BOOTLOADER_VERSION)
                                                    ^
src/main.c:136:52: note: each undeclared identifier is reported only once for each function it appears in
make[1]: *** [../build/target/bootloader/platform-6-lto/./src/main.o] Error 1
make: *** [bootloader] Error 2
```

**Comment by mrmowgli** [comment]
Yeah. I know why.  But it means some more hacking about.  Still it's progress.

Unfortunately I think I also now have to manually do this for the linker as well.

**Pull request closed without merging**
