### PR TITLE
A little consolidation, changes to the arm-gcc-abi-none install on linux, pause function

### PR DESCRIPTION
**Pull request by mrmowgli**
Created the changes I mentioned for gcc install on Linux.  Minor consolidation and case changes, added a pause function and prompt to put the device in DFU mode before patching or updating.

### CODE REVIEW

**Comment by nrobinson2000** [comment]
Can you please merge again to master?  There are a lot of conflicts.  I'll probably resolve the conflicts tonight myself, but if you want to do it today you can.

**Comment by nrobinson2000** [comment]
I resolved the conflicts and merged this.

**Comment by nrobinson2000** [comment]
The linux build failed on travis ci https://travis-ci.org/nrobinson2000/po-util/jobs/136102362

**Comment by nrobinson2000** [comment]
But circle ci passed https://circleci.com/gh/nrobinson2000/po-util/250

**Comment by mrmowgli** [comment]
We pause during the patch / update commands, perhaps it hangs on that?

**Comment by mrmowgli** [comment]
Got it, checking it out now.

**Comment by mrmowgli** [comment]
There's also this, which seems weird on line 656:

```
make[1]: Entering directory `/home/travis/bin/gcc-arm-embedded/dfu-util-0.9/src'
  CCLD     dfu-util
 dfu_util.o: In function `get_path':
/home/travis/bin/gcc-arm-embedded/dfu-util-0.9/src/dfu_util.c:296: undefined reference to `libusb_get_port_numbers'
collect2: ld returned 1 exit status
make[1]: *** [dfu-util] Error 1
make[1]: Leaving directory `/home/travis/bin/gcc-arm-embedded/dfu-util-0.9/src'
make: *** [install-recursive] Error 1
```

**Comment by mrmowgli** [comment]
Interesting.  From what I can see it had trouble downloading gcc from a temporary redirect, and maybe pulled down an older version?  Does re-running the travis test still fail?

**Comment by nrobinson2000** [comment]
I just re-ran it.  It failed again. I think its something do with the $BINDIR variable not being read properly.

**Comment by mrmowgli** [comment]
Probably.  I looked through the make files and didn't see anything specific.  Perhaps create a branch, revert trunk and then add some debug statements around everything, including one that checks gcc version.   

Also after looking at the make file that quits, it looks like we might need to define:
`$(GCC_ARM_PATH)` for the make file, since it's probably building it's path differently.  Odd how it only fails on Travis though.

**Comment by nrobinson2000** [comment]
Yeah.  It might be a problem with Travis.

**Comment by nrobinson2000** [comment]
I just looked, and BINDIR is not saved to the settings file.

```
f [ ! -f $SETTINGS ]
then
  echo BASE_FIRMWARE="$BASE_FIRMWARE" >> $SETTINGS
  echo BRANCH="latest" >> $SETTINGS
  echo PARTICLE_DEVELOP=1 >> $SETTINGS
  echo BINDIR="$BINDIR"
fi
```

I'll try fixing this.

EDIT: This shouldn't be a problem really because BINDIR is defined here:

```
# Mac OSX uses lowercase f for stty command
if [ "$(uname -s)" == "Darwin" ];
  then
    OS="Darwin"
    STTYF="-f"
    MODEM="$(ls -1 /dev/cu.* | grep -vi bluetooth | tail -1)"
  else
    OS="Linux"
    STTYF="-F"
    BINDIR=~/bin
    MODEM="$(ls -1 /dev/* | grep "ttyACM" | tail -1)"
    # Runs script commands with our specific version of GCC from local.  May not need to be exported.
    export PATH=$BINDIR/gcc-arm-embedded/gcc-arm-none-eabi-4_8-2014q2/bin:$PATH
    MESSAGE="$PATH" ; blue_echo
  fi
```

**Comment by nrobinson2000** [comment]
Maybe it is because $PATH is not read properly.

When I tested po-util on my Linux Mint desktop last night with your changes, I had to open a new terminal in order for gcc-arm-embedded to work.

**Comment by mrmowgli** [comment]
See that's strange, we set and export the path at the beginning of the script.  So either A) we never set at the beginning for build (And I'm pretty sure that it gets used when we build dfu-util)  or B) the context is reset somehow between calls, or C) Make isn't using the correct paths.  Perhaps we need a configure step in there.

**Comment by mrmowgli** [comment]
Another possibility is that since the folder doesn't exist yet, it's not setting the path. Adding more messaging.

**Comment by mrmowgli** [comment]
Ok I have it reproducing, checking into it now.

**Pull request merged**
